[supervisord]
nodaemon=true
user=root
pidfile=/run/supervisord.pid

[program:kresd1]
command=/usr/sbin/kresd -c /etc/knot-resolver/kresd.conf -n
environment=SYSTEMD_INSTANCE=1
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:kresd2]
command=/usr/sbin/kresd -c /etc/knot-resolver/kresd.conf -n
environment=SYSTEMD_INSTANCE=2
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:path-proxy]
command=/root/path/proxy.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
